# Generated by Django 5.1.1 on 2024-11-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamescore",
            name="completion_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamescore",
            name="score",
            field=models.IntegerField(),
        ),
    ]
